env:
  - TAG=tkpapp/cmdstan-docker

os: linux

dist: trusty

sudo: required

services:
  - docker

notifications:
  email: false

script:
  - docker build --tag $TAG .
  - docker run -t -a STDIN -a STDERR -a STDOUT $TAG cmdstan/bin/stanc --version
  - docker run -t -a STDIN -a STDERR -a STDOUT $TAG make -C cmdstan examples/bernoulli/bernoulli
